apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node
  name: node
  namespace: apps
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node
status:
  loadBalancer: {}
